// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package xmarket.server.entity.transfer;

public interface RegisterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xmarket.server.entity.transfer.Register)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>optional string phone = 3;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>optional string phone = 3;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
